###
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: openaide/docs-fe
    volumes:
      - ./frontend/src:/app/src
    environment:
      # - VITE_API_HOST=http://localhost:7091
      - VITE_API_HOST=http://docs.openaide.localhost
      - VITE_API_STREAMING=false
    # ports:
    #   - "5173:5173"
    command: ["npm", "run", "dev", "--" , "--host", "0.0.0.0"]
    depends_on:
      - backend

  backend:
    build:
      context: ./application
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: openaide/docs-be
    environment:
      - API_KEY=$OPENAI_API_KEY
      - EMBEDDINGS_KEY=$OPENAI_API_KEY
      - LLM_NAME=openai
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - MONGO_URI=mongodb://mongo:27017/docsgpt
      - CACHE_REDIS_URL=redis://redis:6379/2
    # ports:
    #   - "7091:7091"
    volumes:
      - ./application/indexes:/app/application/indexes
      - ./application/inputs:/app/application/inputs
      - ./application/vectors:/app/application/vectors
    # depends_on:
    #   - redis
    #   - mongo

  worker:
    build:
      context: ./application
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: openaide/docs-worker
    command: celery -A application.app.celery worker -l INFO -B
    environment:
      - API_KEY=$OPENAI_API_KEY
      - EMBEDDINGS_KEY=$OPENAI_API_KEY
      - LLM_NAME=openai
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - MONGO_URI=mongodb://mongo:27017/docsgpt
      - API_URL=http://backend:7091
      - CACHE_REDIS_URL=redis://redis:6379/2
    # depends_on:
    #   - redis
    #   - mongo

  # https://hub.docker.com/_/mongo
  mongo:
    image: mongo:6
    # ports:
    #   - 27017:27017
    volumes:
      - mongodb-data:/data/db
    restart: always
    # labels:
    #   - traefik.enable=true
    #   - traefik.docker.network=openland
    #   # - traefik.http.routers.mongo.rule=Host(`mongo.openaide.localhost`)
    #   # - traefik.http.routers.mongo.entryPoints=web
    #   # - traefik.http.services.mongo.loadbalancer.server.port=27017
    #   - custom.traefik.group=openaide


volumes:
  mongodb-data:

###
    